/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppSettings: typeof import('./src/components/AppSettings.vue')['default']
    CropVisualizer: typeof import('./src/components/CropVisualizer.vue')['default']
    EnhancePage: typeof import('./src/components/EnhancePage.vue')['default']
    EnhanceSettings: typeof import('./src/components/EnhanceSettings.vue')['default']
    FilterPage: typeof import('./src/components/FilterPage.vue')['default']
    FilterSettings: typeof import('./src/components/FilterSettings.vue')['default']
    HomePage: typeof import('./src/components/HomePage.vue')['default']
    InputPage: typeof import('./src/components/InputPage.vue')['default']
    LeftTabBar: typeof import('./src/components/LeftTabBar.vue')['default']
    LogPanel: typeof import('./src/components/LogPanel.vue')['default']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    OutputPage: typeof import('./src/components/OutputPage.vue')['default']
    OutputSettings: typeof import('./src/components/OutputSettings.vue')['default']
    RendingPage: typeof import('./src/components/RendingPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingPage: typeof import('./src/components/SettingPage.vue')['default']
    SettingsModal: typeof import('./src/components/SettingsModal.vue')['default']
    SettingsPanel: typeof import('./src/components/SettingsPanel.vue')['default']
    ThemeSettings: typeof import('./src/components/ThemeSettings.vue')['default']
    Versions: typeof import('./src/components/Versions.vue')['default']
    VideoPreview: typeof import('./src/components/VideoPreview.vue')['default']
  }
}
