/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CropVisualizer: typeof import('./src/components/CropVisualizer.vue')['default']
    EnhanceSettings: typeof import('./src/components/EnhanceSettings.vue')['default']
    FilterSettings: typeof import('./src/components/FilterSettings.vue')['default']
    LogPanel: typeof import('./src/components/LogPanel.vue')['default']
    NDivider: typeof import('naive-ui')['NDivider']
    NIcon: typeof import('naive-ui')['NIcon']
    NModal: typeof import('naive-ui')['NModal']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    OutputSettings: typeof import('./src/components/OutputSettings.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsModal: typeof import('./src/components/SettingsModal.vue')['default']
    SettingsPanel: typeof import('./src/components/SettingsPanel.vue')['default']
    ThemeSettings: typeof import('./src/components/ThemeSettings.vue')['default']
    VideoPreview: typeof import('./src/components/VideoPreview.vue')['default']
  }
}
